/*
 * atomic_lock_prefix_alignment_shift_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef ATOMIC_LOCK_PREFIX_ALIGNMENT_SHIFT_STRATEGIES_H
#define ATOMIC_LOCK_PREFIX_ALIGNMENT_SHIFT_STRATEGIES_H

void register_atomic_lock_prefix_alignment_shift_strategies(void);

#endif /* ATOMIC_LOCK_PREFIX_ALIGNMENT_SHIFT_STRATEGIES_H */