/*
 * bmi1_andn_logic_transformation_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef BMI1_ANDN_LOGIC_TRANSFORMATION_STRATEGIES_H
#define BMI1_ANDN_LOGIC_TRANSFORMATION_STRATEGIES_H

void register_bmi1_andn_logic_transformation_strategies(void);

#endif /* BMI1_ANDN_LOGIC_TRANSFORMATION_STRATEGIES_H */