/*
 * bmi1_bextr_bitfield_extraction_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef BMI1_BEXTR_BITFIELD_EXTRACTION_STRATEGIES_H
#define BMI1_BEXTR_BITFIELD_EXTRACTION_STRATEGIES_H

void register_bmi1_bextr_bitfield_extraction_strategies(void);

#endif /* BMI1_BEXTR_BITFIELD_EXTRACTION_STRATEGIES_H */