/*
 * bmi2_bzhi_bit_masking_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef BMI2_BZHI_BIT_MASKING_STRATEGIES_H
#define BMI2_BZHI_BIT_MASKING_STRATEGIES_H

void register_bmi2_bzhi_bit_masking_strategies(void);

#endif /* BMI2_BZHI_BIT_MASKING_STRATEGIES_H */