/*
 * bmi2_flags_preserving_shift_transformation_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef BMI2_FLAGS_PRESERVING_SHIFT_TRANSFORMATION_STRATEGIES_H
#define BMI2_FLAGS_PRESERVING_SHIFT_TRANSFORMATION_STRATEGIES_H

void register_bmi2_flags_preserving_shift_transformation_strategies(void);

#endif /* BMI2_FLAGS_PRESERVING_SHIFT_TRANSFORMATION_STRATEGIES_H */