/*
 * bmi2_mulx_dual_register_transformation_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef BMI2_MULX_DUAL_REGISTER_TRANSFORMATION_STRATEGIES_H
#define BMI2_MULX_DUAL_REGISTER_TRANSFORMATION_STRATEGIES_H

void register_bmi2_mulx_dual_register_transformation_strategies(void);

#endif /* BMI2_MULX_DUAL_REGISTER_TRANSFORMATION_STRATEGIES_H */