/*
 * lsl_segment_limit_constant_substitution_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef LSL_SEGMENT_LIMIT_CONSTANT_SUBSTITUTION_STRATEGIES_H
#define LSL_SEGMENT_LIMIT_CONSTANT_SUBSTITUTION_STRATEGIES_H

void register_lsl_segment_limit_constant_substitution_strategies(void);

#endif /* LSL_SEGMENT_LIMIT_CONSTANT_SUBSTITUTION_STRATEGIES_H */