/*
 * non_temporal_move_substitution_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef NON_TEMPORAL_MOVE_SUBSTITUTION_STRATEGIES_H
#define NON_TEMPORAL_MOVE_SUBSTITUTION_STRATEGIES_H

void register_non_temporal_move_substitution_strategies(void);

#endif /* NON_TEMPORAL_MOVE_SUBSTITUTION_STRATEGIES_H */