/*
 * segment_limit_constant_loading_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef SEGMENT_LIMIT_CONSTANT_LOADING_STRATEGIES_H
#define SEGMENT_LIMIT_CONSTANT_LOADING_STRATEGIES_H

void register_segment_limit_constant_loading_strategies(void);

#endif /* SEGMENT_LIMIT_CONSTANT_LOADING_STRATEGIES_H */