/*
 * segment_register_load_pointer_construction_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef SEGMENT_REGISTER_LOAD_POINTER_CONSTRUCTION_STRATEGIES_H
#define SEGMENT_REGISTER_LOAD_POINTER_CONSTRUCTION_STRATEGIES_H

void register_segment_register_load_pointer_construction_strategies(void);

#endif /* SEGMENT_REGISTER_LOAD_POINTER_CONSTRUCTION_STRATEGIES_H */