/*
 * shrd_double_precision_value_synthesis_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef SHRD_DOUBLE_PRECISION_VALUE_SYNTHESIS_STRATEGIES_H
#define SHRD_DOUBLE_PRECISION_VALUE_SYNTHESIS_STRATEGIES_H

void register_shrd_double_precision_value_synthesis_strategies(void);

#endif /* SHRD_DOUBLE_PRECISION_VALUE_SYNTHESIS_STRATEGIES_H */