/*
 * vex_escape_byte_remapping_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_ESCAPE_BYTE_REMAPPING_STRATEGIES_H
#define VEX_ESCAPE_BYTE_REMAPPING_STRATEGIES_H

void register_vex_escape_byte_remapping_strategies(void);

#endif /* VEX_ESCAPE_BYTE_REMAPPING_STRATEGIES_H */