/*
 * vex_avx512_immediate_construction_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_AVX512_IMMEDIATE_CONSTRUCTION_STRATEGIES_H
#define VEX_AVX512_IMMEDIATE_CONSTRUCTION_STRATEGIES_H

void register_vex_avx512_immediate_construction_strategies(void);

#endif /* VEX_AVX512_IMMEDIATE_CONSTRUCTION_STRATEGIES_H */