/*
 * vex_evx_prefix_byte_remapping_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_EVX_PREFIX_BYTE_REMAPPING_STRATEGIES_H
#define VEX_EVX_PREFIX_BYTE_REMAPPING_STRATEGIES_H

void register_vex_evx_prefix_byte_remapping_strategies(void);

#endif /* VEX_EVX_PREFIX_BYTE_REMAPPING_STRATEGIES_H */