/*
 * vex_evex_prefix_remapping_for_avx_immediate_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_EVEX_PREFIX_REMAPPING_FOR_AVX_IMMEDIATE_STRATEGIES_H
#define VEX_EVEX_PREFIX_REMAPPING_FOR_AVX_IMMEDIATE_STRATEGIES_H

void register_vex_evex_prefix_remapping_for_avx_immediate_strategies(void);

#endif /* VEX_EVEX_PREFIX_REMAPPING_FOR_AVX_IMMEDIATE_STRATEGIES_H */