/*
 * vex_evx_prefix_modrm_remap_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_EVX_PREFIX_MODRM_REMAP_STRATEGIES_H
#define VEX_EVX_PREFIX_MODRM_REMAP_STRATEGIES_H

void register_vex_evx_prefix_modrm_remap_strategies(void);

#endif /* VEX_EVX_PREFIX_MODRM_REMAP_STRATEGIES_H */