/*
 * vex_evx_immediate_encoding_shift_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_EVX_IMMEDIATE_ENCODING_SHIFT_STRATEGIES_H
#define VEX_EVX_IMMEDIATE_ENCODING_SHIFT_STRATEGIES_H

void register_vex_evx_immediate_encoding_shift_strategies(void);

#endif /* VEX_EVX_IMMEDIATE_ENCODING_SHIFT_STRATEGIES_H */