/*
 * vex_xmm_gpr_bridge_substitution_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_XMM_GPR_BRIDGE_SUBSTITUTION_STRATEGIES_H
#define VEX_XMM_GPR_BRIDGE_SUBSTITUTION_STRATEGIES_H

void register_vex_xmm_gpr_bridge_substitution_strategies(void);

#endif /* VEX_XMM_GPR_BRIDGE_SUBSTITUTION_STRATEGIES_H */