/*
 * vex_encoding_byte_evasion_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_ENCODING_BYTE_EVASION_STRATEGIES_H
#define VEX_ENCODING_BYTE_EVASION_STRATEGIES_H

void register_vex_encoding_byte_evasion_strategies(void);

#endif /* VEX_ENCODING_BYTE_EVASION_STRATEGIES_H */