/*
 * vex_escape_badbyte_evasion_strategies.h
 * Auto-generated by BYVALVER CodeGenerationAgent
 */
#ifndef VEX_ESCAPE_BADBYTE_EVASION_STRATEGIES_H
#define VEX_ESCAPE_BADBYTE_EVASION_STRATEGIES_H

void register_vex_escape_badbyte_evasion_strategies(void);

#endif /* VEX_ESCAPE_BADBYTE_EVASION_STRATEGIES_H */